version: '3.8'

services:
  db:
    container_name: db
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: brogrammers-team
      MYSQL_USER: brogrammers
      MYSQL_PASSWORD: BrogrammersMe10
      MYSQL_ROOT_PASSWORD: Brogrammers_Root_pass
    networks:
      [brogrammers-team-net]

  app-server:
    container_name: brogrammers-team
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/brogrammers-team
      SPRING_DATASOURCE_USERNAME: brogrammers
      SPRING_DATASOURCE_PASSWORD: BrogrammersMe10
    networks:
      - brogrammers-team-net

networks:
  brogrammers-team-net: