version: '3.8'

services:
  brogramm-db:
    container_name: brogramm-db
    image: mysql
    ports:
      - "3306:3306"
#    restart: unless-stopped
    environment:
      MYSQL_DATABASE: brogrammers-registration
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    networks:
      [brogrammers-team-net]

  app-server:
    container_name: brogrammers-team
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
#    restart: unless-stopped

    depends_on:
      - brogramm-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://brogramm-db:3306/brogrammers-registration?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - brogrammers-team-net

networks:
  brogrammers-team-net:
